[package]
name = "fqparser"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.3"
bio = "1.3.1"
rayon = "1.7.0"
dashmap = "5.5.0"
needletail = "0.5.1"
